language: android 
android:
  components:
    - build-tools-20.0.0
    - android-20
jdk: oraclejdk8

cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/modules-2/files-2.1

before_install:
- chmod +x gradlew


before_deploy:
- ./gradlew desktop:dist
- mv desktop/build/libs/desktop-1.0.jar desktop/build/libs/{PROJECT_NAME}-$TRAVIS_TAG.jar
- ./gradlew android:assembleRelease
- mv android/build/outputs/apk/android-release-unsigned.apk android/build/outputs/apk/{PROJECT_NAME}-$TRAVIS_TAG-unaligned.apk
- ./gradlew html:dist
- zip -r {PROJECT_NAME}-$TRAVIS_TAG.zip ./html/build/dist/
deploy:
  provider: releases
  api_key:
    secure: {DEPLOYMENT_KEY}
  file:
  - desktop/build/libs/{PROJECT_NAME}-$TRAVIS_TAG.jar
  - android/build/outputs/apk/{PROJECT_NAME}-$TRAVIS_TAG-unaligned.apk
  - {PROJECT_NAME}-$TRAVIS_TAG.zip
  on:
    tags: true
    repo: {GITHUB_USER}/{PROJECT_NAME}
    branches: master
    condition: "$TRAVIS_TAG =~ ^v\d+\.\d+\.\d+.*$"
